### ISSUE TITLE
PredictMod v1.1 Descriptive Text

### ISSUE THREAD

**Issue by lorikrammer** [GW-HIVE/PredictMod#109]
We will need to have some descriptive text in PredictMod v1.1 describing metagenomic and EHR data.
1. Where the data is coming from
2. What is being done in the analysis step
3. What the results mean
etc.

**Comment by ubhuiyan** [comment]
EHR:
Electronic health records or EHR comprise patient-centered records that contain all clinically relevant information to streamline clinician workflow. This information can play a crucial role in facilitating precision medicine by providing comprehensive and accessible patient data that can be leveraged to personalize healthcare. The machine learning (ML) model for “EHR Prediction” is trained on synthetic patient data that mimics the statistics of the real US population with respect to demographics and disease burden. When a single patient file is submitted, the trained EHR model will analyze the variables of the individual with unknown response, and generate a prediction of responder (R) or non-responder (NR) based on the characteristics of their EHR variables. 

EHR Instructions: 
Begin by viewing the sample table provided [insert url/attachment]. Input data must look similar in format to the sample table provided in order to receive the most accurate prediction. Attach either the sample table or other anonymized input table into the search box labeled “EHR Prediction” and click submit. A prediction of R or NR will be provided shortly after submission. This indicates the patient's predicted response outcome to diet modifications typical of a self-management plan for the treatment of prediabetes. 

MG:
The gut microbiome consists of the genetic material, or the metagenome (MG), of microbial communities found within the human gastrointestinal tract that has emerged as a key area of research in understanding the intricate relationship between the microbiome and human well-being. Understanding the role of the gut microbiome can pave the way for new interventions and treatments to provide targeted therapies. The metagenomic sequences used to train the ML model for “MG Prediction” were derived from NCBI SRA accession: PRJNA454826. When a single patient file is submitted, the trained MG model will analyze the variables of the individual with unknown response, and generate a prediction of responder (R) or non-responder (NR) based on the characteristics of their MG abundances. 

MG Instructions: 
Begin by viewing the sample table provided [insert url/attachment]. Input data must look similar in format to the sample table provided in order to receive the most accurate prediction. Attach either the sample table or other anonymized input table into the search box labeled “MG Prediction” and click submit. A prediction of R or NR will be provided shortly after submission. This indicates the patient’s predicted response outcome to exercise for the treatment of prediabetes.
