### ISSUE TITLE
Milestone & Timeline Updates

### ISSUE THREAD

**Issue by lorikrammer** [GW-HIVE/PredictMod#117]
**Primary: Lori | Backup: Steph**
- [ ] Timeline & breakdown of milestones for Y1, Y2, Y3. 6 month development timeline, track when we think we'll start vs when we actually start.

**Comment by lorikrammer** [comment]
@steph-sing If you get a chance, please take a look at the milestones document here (Documents > Product Management > Milestones & Timeline) and provide feedback. Specifically, I would like to verify that our interpretation and deliverables columns are appropriate to the project and feasible. I am happy to clarify this task further. Thanks!

**Comment by steph-sing** [comment]
@lorikrammer received. I will start this on Thursday Aug 31.

**Comment by steph-sing** [comment]
Starting here with structure since my biology brain goes straight to 'structure = function'. Let me know if you want to discuss as it might be confusing. If you don't agree with these suggestions, I will take another pass and do my best to sift through these columns.

- I don't understand the necessity for columns J,K,L, or N unless they were specifically requested. Its a lot of extra work for you, and slightly confusing. I would remove.

-  I might be easier to better utilize your 'Status' column and track/update those items per your reporting cycle, like you do in the reports, and just label complete or not started if not in progress. If in progress, it can have a detailed update per reporting cycle like in your reports. This means you could copy/paste and save time on the reporting if the structure is the same. In this case, you really would not need J,K,L, or N (again, unless specifically requested)

- Activity, Interpretation, and Deliverable seem redundant, I would consider condensing in the following way: (1) keep Activity (don't alter, this matches the PMP) and either condense the information from the other two columns into the Deliverable column, or (2) keep Activity and Deliverable the same and move the Interpretation information into the Note column. what ever makes it as simple, clear, and concise as possible for you and others, particularly with reporting in mind. The word 'Interpretation' leaves a lot of room for subjectivity and that may not necessarily be a good thing when committing to deliverables

**Comment by lorikrammer** [comment]
This is great feedback, thank you! I agree with these changes and will update the Milestones document accordingly.
