### ISSUE TITLE
Calling MatLab from inside Docker

### ISSUE THREAD

**Issue by pmcneely** [GW-HIVE/PredictMod#79]
@rykahsay please send me info or notes about how you've made calls from containerized apps to MatLab running on the host. It's good to reuse a tried and true method!

@pmcneely will finish building the predictmod container afterward.

**Comment by rykahsay** [comment]
These instructions show you how to run a shell script ("glycan_finder.sh") on the host from a container. In this case the script "glycan_finder.sh" uses MatLab which is only available on the host only.


###  Make directory and then make fifo
```
$ mkdir -p /software/pipes/
$ mkfifo /software/pipes/mypipe
```

### Create /software/pipes/execpipe.sh with the following content
```    
#!/bin/bash    
out_file="/data/shared/glygen/pipe_output/output.txt"    
while true; do eval "$(cat /software/pipes/mypipe)" &> $out_file; done
```

###  Add to cronjobs so that it starts on boot
```
$ sudo crontab -e
@reboot /software/pipes/execpipe.sh
```

### Use docker run as follows to mount /software/pipes folder of the host
```    
sudo docker run -dit --name $docker_container -p 127.0.0.1:$port:80  -v /software/pipes:/hostpipe $docker_image
```

### Now your script  /software/pipes/glycan_finder.sh can be executed in the container as 
```    
$ sh /hostpipe/glycan_finder.sh  
```
